version: "3.3"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion:latest
    volumes_from:
        - nginx-proxy
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - acme:/etc/acme.sh

  gateway:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
    - VIRTUAL_HOST=app.example.com
    - LETSENCRYPT_HOST=app.example.com
    - LETSENCRYPT_EMAIL=albert_h@example.com
    - DEFAULT_EMAIL=albert_h@example.com

  backend:
    image: containous/whoami
  
  frontend:
    image: containous/whoami


volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
